# Generated by Django 3.2.8 on 2023-02-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20230223_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition_Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio_app/images')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.exhibition')),
            ],
        ),
    ]
