# Generated by Django 3.2.8 on 2023-02-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_exhibition_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exhibition_Views',
            new_name='Exhibition_View',
        ),
    ]
