# Generated by Django 3.2.8 on 2023-02-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_rename_exhibition_views_exhibition_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='ubication',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
