# Generated by Django 3.2.8 on 2023-02-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_auto_20230223_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='url',
        ),
    ]
