# Generated by Django 4.1.3 on 2023-02-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0009_alter_exhibition_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="exhibition_view",
            name="description",
            field=models.TextField(max_length=250),
        ),
    ]
