# Generated by Django 3.2.8 on 2023-03-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_alter_exhibition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
