# Generated by Django 3.2.8 on 2023-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_exhibition_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(upload_to='portfolio_app/images/image_%(id)s/'),
        ),
        migrations.AlterField(
            model_name='exhibition_view',
            name='image',
            field=models.ImageField(upload_to='portfolio_app/images_%(id)s/galery/'),
        ),
    ]
