# Generated by Django 4.1.3 on 2023-04-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0017_alter_exhibition_date_alter_exhibition_ubication"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="password",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
