# Generated by Django 4.1.3 on 2023-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0019_exhibition_hidden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibition_view",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="exhibition_view",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Order for display"),
        ),
    ]
