# Generated by Django 4.1.3 on 2023-10-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0020_alter_exhibition_view_options_exhibition_view_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiographyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Biography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(max_length=10000)),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio_app.biographytype",
                    ),
                ),
            ],
        ),
    ]
