# Generated by Django 4.1.3 on 2023-10-05 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0021_biographytype_biography"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biographytype",
            old_name="type_name",
            new_name="name",
        ),
    ]
