# Generated by Django 4.1.3 on 2023-10-05 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0022_rename_type_name_biographytype_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biography",
            old_name="type_id",
            new_name="type",
        ),
    ]
