# Generated by Django 4.1.3 on 2023-10-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0024_rename_type_biography_biography_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="biography",
            name="related_biography",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio_app.biography",
            ),
        ),
    ]
