# Generated by Django 4.1.3 on 2023-10-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0025_biography_related_biography"),
    ]

    operations = [
        migrations.CreateModel(
            name="Biography_Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(max_length=10000)),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.RemoveField(
            model_name="biography",
            name="biography_type",
        ),
        migrations.RemoveField(
            model_name="biography",
            name="date",
        ),
        migrations.RemoveField(
            model_name="biography",
            name="description",
        ),
        migrations.RemoveField(
            model_name="biography",
            name="related_biography",
        ),
        migrations.AddField(
            model_name="biography",
            name="title",
            field=models.CharField(default="Biography", max_length=100),
        ),
        migrations.DeleteModel(
            name="BiographyType",
        ),
        migrations.AddField(
            model_name="biography_content",
            name="biography",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio_app.biography",
            ),
        ),
        migrations.AddField(
            model_name="biography_content",
            name="related_biography",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio_app.biography_content",
            ),
        ),
    ]
