# Generated by Django 4.1.3 on 2023-10-26 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio_app",
            "0026_biography_content_remove_biography_biography_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biography_content",
            name="related_biography",
        ),
    ]
