# Generated by Django 4.1.3 on 2023-10-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0027_remove_biography_content_related_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="biography_content",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
