# Generated by Django 4.1.3 on 2023-11-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0028_biography_content_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biography_content",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="biography_content",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
