# Generated by Django 4.1.3 on 2023-11-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0029_alter_biography_content_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biography_content",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biography_content",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
