# Generated by Django 4.1.3 on 2023-04-02 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_auto_20230225_0156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name=datetime.date.today
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name=datetime.date.today
            ),
        ),
    ]
