# Generated by Django 4.1.3 on 2023-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_alter_post_end_date_alter_post_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=10000),
        ),
    ]
