# Generated by Django 4.1.3 on 2023-04-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_alter_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
