# Generated by Django 4.1.3 on 2023-11-18 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0006_alter_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="blog_app/pdfs"),
        ),
        migrations.AlterField(
            model_name="post",
            name="end_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="start_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
